name: CI
on: [pull_request]
jobs:
  test:
    runs-on: [windows-2019]
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
    steps:
      - uses: actions/checkout@v1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: pip install -r requirements_test.txt
      - name: unit
        run: pytest test/unit
