name: CI
on: [push, 	pull_request]
jobs:
  test:
    runs-on: ubuntu-latest  # TODO specify disto and version
    strategy:
      matrix:
        python-version: ["3.10"]  # TODO specify python version
    steps:
      - uses: actions/checkout@v1
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: pip install -r requirements_test.txt
      - name: unit
        run: pytest test/unit
