name: CI
on: pull_request

jobs:

  test:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04, windows-2019]
        python-version: [3.7, 3.10]

    steps:

      - name: setup ${{ matrix.os }} ${{ matrix.python-version }}
        uses: actions/checkout@v1
        uses: actions/setup-python@v1
        run: pip install -r requirements_test.txt

      - name: unit
        run: pytest test/unit
